global timeLineFlag
global cameraScreenFlag
global reportFlag
global toolsListText
global toolsListIndex
global ui
global report
global sourcePath
global resultPath
global ChangeColorIndex
global ChangeColorFlag
