# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 720)
        MainWindow.setMinimumSize(QtCore.QSize(960, 720))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 590, 331, 81))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.registerImagesButton = QtWidgets.QPushButton(self.groupBox)
        self.registerImagesButton.setGeometry(QtCore.QRect(30, 20, 130, 50))
        self.registerImagesButton.setMinimumSize(QtCore.QSize(130, 50))
        self.registerImagesButton.setObjectName("registerImagesButton")
        self.runButton = QtWidgets.QPushButton(self.groupBox)
        self.runButton.setGeometry(QtCore.QRect(170, 20, 130, 50))
        self.runButton.setMinimumSize(QtCore.QSize(130, 50))
        self.runButton.setObjectName("runButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 209, 600, 461))
        self.groupBox_2.setMinimumSize(QtCore.QSize(600, 450))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.cameraLabel = QtWidgets.QLabel(self.groupBox_2)
        self.cameraLabel.setGeometry(QtCore.QRect(19, 30, 540, 405))
        self.cameraLabel.setMinimumSize(QtCore.QSize(100, 405))
        self.cameraLabel.setMaximumSize(QtCore.QSize(540, 405))
        self.cameraLabel.setObjectName("cameraLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 941, 121))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.addTool = QtWidgets.QPushButton(self.groupBox_3)
        self.addTool.setGeometry(QtCore.QRect(40, 40, 65, 50))
        self.addTool.setMinimumSize(QtCore.QSize(65, 50))
        self.addTool.setObjectName("addTool")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setGeometry(QtCore.QRect(150, 20, 781, 91))
        self.scrollArea.setLineWidth(5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 601, 81))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.SaveProgramButton = QtWidgets.QPushButton(self.groupBox_4)
        self.SaveProgramButton.setGeometry(QtCore.QRect(10, 20, 65, 50))
        self.SaveProgramButton.setMinimumSize(QtCore.QSize(65, 50))
        self.SaveProgramButton.setObjectName("SaveProgramButton")
        self.LoadProgramButton = QtWidgets.QPushButton(self.groupBox_4)
        self.LoadProgramButton.setGeometry(QtCore.QRect(80, 20, 65, 50))
        self.LoadProgramButton.setMinimumSize(QtCore.QSize(65, 50))
        self.LoadProgramButton.setObjectName("LoadProgramButton")
        self.ProgramName = QtWidgets.QLineEdit(self.groupBox_4)
        self.ProgramName.setGeometry(QtCore.QRect(270, 30, 131, 31))
        self.ProgramName.setObjectName("ProgramName")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(170, 40, 91, 16))
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(620, 10, 331, 80))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 20, 65, 50))
        self.pushButton_11.setMinimumSize(QtCore.QSize(65, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_12.setGeometry(QtCore.QRect(150, 20, 65, 50))
        self.pushButton_12.setMinimumSize(QtCore.QSize(65, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 20, 65, 50))
        self.pushButton_13.setMinimumSize(QtCore.QSize(65, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_6.setGeometry(QtCore.QRect(620, 220, 331, 361))
        self.groupBox_6.setObjectName("groupBox_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_6)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 20, 301, 331))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 299, 329))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Report_Label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.Report_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Report_Label.setObjectName("Report_Label")
        self.verticalLayout.addWidget(self.Report_Label)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Capture"))
        self.registerImagesButton.setText(_translate("MainWindow", "Register Images"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Camera "))
        self.cameraLabel.setText(_translate("MainWindow", "Camera Screen"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tool Timeline"))
        self.addTool.setText(_translate("MainWindow", "Add Tool"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Program"))
        self.SaveProgramButton.setText(_translate("MainWindow", "Save"))
        self.LoadProgramButton.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "Program Name:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Settings"))
        self.pushButton_11.setText(_translate("MainWindow", "Execute"))
        self.pushButton_12.setText(_translate("MainWindow", "Utility"))
        self.pushButton_13.setText(_translate("MainWindow", "Output"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.Report_Label.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

